// <auto-generated />
using System;
using LeadAnalytics.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadAnalytics.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327181526_LeadsNameTableUpdate")]
    partial class LeadsNameTableUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadAnalytics.Api.DTOs.TagDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("TagDto");

                    b.HasAnnotation("Relational:JsonPropertyName", "tags");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("ConversationState")
                        .HasColumnType("text")
                        .HasJsonPropertyName("conversationState");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasJsonPropertyName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasJsonPropertyName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasJsonPropertyName("gender");

                    b.Property<string>("IdFacebookApp")
                        .HasColumnType("text")
                        .HasJsonPropertyName("idfacebookapp");

                    b.Property<int?>("IdStage")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id_stage");

                    b.Property<string>("LastAdId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("last_ad_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasJsonPropertyName("observations");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("phone");

                    b.Property<string>("Stage")
                        .HasColumnType("text")
                        .HasJsonPropertyName("stage");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("clinic_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("last_updated_at");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric")
                        .HasJsonPropertyName("value");

                    b.HasKey("Id");

                    b.HasIndex("Id", "TenantId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("LeadAnalytics.Api.DTOs.TagDto", b =>
                {
                    b.HasOne("LeadAnalytics.Api.Models.Lead", null)
                        .WithMany("Tags")
                        .HasForeignKey("LeadId");
                });

            modelBuilder.Entity("LeadAnalytics.Api.Models.Lead", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
